version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ehpj-stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ehpj-stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ehpj-service:
    build: ./main
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - ehpj-db
      - stats-server
    environment:
    - CLIENT_URL=http://stats-server:9090
    - SPRING_DATASOURCE_URL=jdbc:postgresql://ehpj-db:5432/ehpj-main

  ehpj-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ehpj-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
